/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VoteVerse;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.*;


/**
 *
 * @author lenovo
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jadminid = new javax.swing.JTextField();
        jvoterid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jreset = new javax.swing.JButton();
        jvreset = new javax.swing.JButton();
        jvoterpw = new javax.swing.JPasswordField();
        jadminpw = new javax.swing.JPasswordField();
        jlogin = new javax.swing.JButton();
        jvlogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(570, 470));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));
        jPanel2.setMinimumSize(new java.awt.Dimension(285, 303));
        jPanel2.setPreferredSize(new java.awt.Dimension(285, 303));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setForeground(new java.awt.Color(51, 0, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VoteVerse/ic_person_white_48dp.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.setMaximumSize(new java.awt.Dimension(96, 96));
        jLabel8.setMinimumSize(new java.awt.Dimension(96, 96));
        jLabel8.setPreferredSize(new java.awt.Dimension(96, 96));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 187, 221));

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Voting Management System");
        jLabel9.setMaximumSize(new java.awt.Dimension(208, 23));
        jLabel9.setMinimumSize(new java.awt.Dimension(208, 23));
        jLabel9.setPreferredSize(new java.awt.Dimension(208, 23));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 265, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 470));

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setMinimumSize(new java.awt.Dimension(662, 440));
        jPanel1.setPreferredSize(new java.awt.Dimension(662, 440));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jadminid.setForeground(java.awt.Color.red);
        jadminid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jadminid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 208, 30));

        jvoterid.setForeground(java.awt.Color.red);
        jvoterid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jvoterid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 209, 30));

        jLabel1.setText("Admin Name");
        jLabel1.setMaximumSize(new java.awt.Dimension(52, 14));
        jLabel1.setMinimumSize(new java.awt.Dimension(52, 14));
        jLabel1.setPreferredSize(new java.awt.Dimension(52, 14));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 100, 10));

        jPanel6.setBackground(java.awt.Color.red);
        jPanel6.setMaximumSize(new java.awt.Dimension(50, 40));
        jPanel6.setName(""); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(50, 40));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(java.awt.Color.red);
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VoteVerse/clear.png"))); // NOI18N
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setMaximumSize(new java.awt.Dimension(50, 40));
        jButton3.setMinimumSize(new java.awt.Dimension(50, 40));
        jButton3.setPreferredSize(new java.awt.Dimension(50, 40));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 40, 40));

        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel3.setText("Voter ID");
        jLabel3.setMaximumSize(new java.awt.Dimension(39, 14));
        jLabel3.setMinimumSize(new java.awt.Dimension(39, 14));
        jLabel3.setPreferredSize(new java.awt.Dimension(39, 14));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 281, 50, -1));

        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Voter Login");
        jLabel11.setMaximumSize(new java.awt.Dimension(147, 44));
        jLabel11.setMinimumSize(new java.awt.Dimension(147, 44));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Admin Login");
        jLabel12.setMaximumSize(new java.awt.Dimension(147, 44));
        jLabel12.setMinimumSize(new java.awt.Dimension(147, 44));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jreset.setBackground(java.awt.Color.yellow);
        jreset.setForeground(java.awt.Color.blue);
        jreset.setText("Reset");
        jreset.setActionCommand("");
        jreset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jreset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jreset.setMaximumSize(new java.awt.Dimension(43, 25));
        jreset.setMinimumSize(new java.awt.Dimension(43, 25));
        jreset.setPreferredSize(new java.awt.Dimension(43, 25));
        jreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jresetActionPerformed(evt);
            }
        });
        jPanel1.add(jreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 80, 30));

        jvreset.setBackground(java.awt.Color.yellow);
        jvreset.setForeground(java.awt.Color.blue);
        jvreset.setText("Reset");
        jvreset.setActionCommand("");
        jvreset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jvreset.setMaximumSize(new java.awt.Dimension(41, 25));
        jvreset.setMinimumSize(new java.awt.Dimension(41, 25));
        jvreset.setPreferredSize(new java.awt.Dimension(41, 25));
        jvreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jvresetActionPerformed(evt);
            }
        });
        jPanel1.add(jvreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 84, 30));
        jvreset.getAccessibleContext().setAccessibleDescription("");

        jvoterpw.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jvoterpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 208, 30));

        jadminpw.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jadminpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 208, 30));

        jlogin.setBackground(java.awt.Color.yellow);
        jlogin.setForeground(java.awt.Color.blue);
        jlogin.setText("Login");
        jlogin.setActionCommand("");
        jlogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlogin.setMaximumSize(new java.awt.Dimension(41, 25));
        jlogin.setMinimumSize(new java.awt.Dimension(41, 25));
        jlogin.setPreferredSize(new java.awt.Dimension(41, 25));
        jlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloginActionPerformed(evt);
            }
        });
        jPanel1.add(jlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 84, 30));

        jvlogin.setBackground(java.awt.Color.yellow);
        jvlogin.setForeground(java.awt.Color.blue);
        jvlogin.setText("Login");
        jvlogin.setActionCommand("");
        jvlogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jvlogin.setMaximumSize(new java.awt.Dimension(41, 25));
        jvlogin.setMinimumSize(new java.awt.Dimension(41, 25));
        jvlogin.setPreferredSize(new java.awt.Dimension(41, 25));
        jvlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jvloginActionPerformed(evt);
            }
        });
        jPanel1.add(jvlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 84, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 300, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jresetActionPerformed
        jadminid.setText(null);
        jadminpw.setText(null);
        
    }//GEN-LAST:event_jresetActionPerformed

    private void jvresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jvresetActionPerformed
      jvoterid.setText(null);
      jvoterpw.setText(null);
      
    }//GEN-LAST:event_jvresetActionPerformed
    
    private void jloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jloginActionPerformed
      try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/voting_system", "root", "");
            String sql = "select * from admin where name=? and password=? ";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1,jadminid.getText());
            ps.setString(2,String.valueOf(jadminpw.getPassword()));
            
            ResultSet res=ps.executeQuery();
            if(res.next())
            {
                 JOptionPane.showMessageDialog(null, "Correct username and password");
                 
            Home h = new Home();
            h.setVisible(true);
            dispose();
            }
            else
            {
             JOptionPane.showMessageDialog(null, "Access Denied. Invalid username or password.");
            }
      }catch (SQLException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
    }                                       
    }//GEN-LAST:event_jloginActionPerformed

    private void jvloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jvloginActionPerformed
        try {
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/voting_system", "root", "");
            String sql = "select * from addvoter1 where voterid=? and password=? and hasVoted=?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1,jvoterid.getText());
            ps.setString(2,String.valueOf(jvoterpw.getPassword()));
            ps.setInt(3,0);//initially set to 0 when voter votes for the first time
           
            ResultSet res=ps.executeQuery();
            if(res.next())
            {
                 JOptionPane.showMessageDialog(null, "Correct ID and password");
                 String updatesql="update addvoter1 set hasVoted=? where voterid=?";
                 PreparedStatement updateps = con.prepareStatement(updatesql);
                 updateps.setInt(1,1);//?--> placeholder 1
                 updateps.setString(2,jvoterid.getText());
                 updateps.executeUpdate();
                 
           startelection se=new startelection();
           se.setVisible(true);
           dispose();
            }
            else
            {
             JOptionPane.showMessageDialog(null, "Access Denied. Invalid username or password. Eithert that, or you have already voted");
            }
      }catch (SQLException ex) {
            Logger.getLogger(addvoter.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jvloginActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
  java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jadminid;
    private javax.swing.JPasswordField jadminpw;
    private javax.swing.JButton jlogin;
    private javax.swing.JButton jreset;
    private javax.swing.JButton jvlogin;
    private javax.swing.JTextField jvoterid;
    private javax.swing.JPasswordField jvoterpw;
    private javax.swing.JButton jvreset;
    // End of variables declaration//GEN-END:variables
}
